### ISSUE TITLE
Remove deprecated classes/methods from OH3

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-core#1408]
There are quite a few classes and methods marked as `@Deprecated` that can be removed from the OH3 code base.

Classes marked as `@Deprecated` are:

* [x] org.openhab.core.config.discovery.DiscoveryServiceCallback (see #1424)
* [x] org.openhab.core.config.discovery.ExtendedDiscoveryService (see #1424)
* [x] org.openhab.core.config.discovery.UpnpDiscoveryParticipant (see #1418)
* [x] org.openhab.core.config.discovery.inbox.InboxFilterCriteria (see #1417)
* [x] org.openhab.core.types.StateDescriptionProvider (see #1413)
* [x] org.openhab.core.io.net.http.TrustManagerProvider (see #1425)
* [x] org.openhab.core.io.transport.mdns.discovery.MDNSDiscoveryParticipant (see #1418)
* [x] org.openhab.core.io.transport.mqtt.sslcontext.CustomSSLContextProvider (see #1668)
* [x] org.openhab.core.io.transport.mqtt.sslcontext.AcceptAllCertificatesSSLContext (see #1668)
* [x] org.openhab.core.io.transport.mqtt.sslcontext.SSLContextProvider (see #1668)

There are even more methods marked as `@Deprecated`, some examples are:

* [x] org.openhab.core.items.ItemRegistry.newItemBuilder(Item) (see #1429)
* [x] org.openhab.core.items.ItemRegistry.newItemBuilder(String, String) (see #1429)
* [x] org.openhab.core.net.NetUtil.getLocalIpv4HostAddress() (see #1622)
* [x] org.openhab.core.config.core.ConfigOptionProvider.getParameterOptions(URI, String, Locale) (see #1541, #1667)
* [x] org.openhab.core.thing.i18n.ChannelTypeI18nLocalizationService.createLocalizedStateDescription​ (see #1918)
* [x] org.openhab.core.thing.type.StateChannelTypeBuilder.withStateDescription​ (see #1918)

Classes with constructors marked as `@Deprecated`:

* [x] org.openhab.core.config.core.ConfigDescriptionParameterGroup​ (see #1918)
* [x] org.openhab.core.thing.Channel​ (see #1918)
* [x] org.openhab.core.thing.type.ChannelType​ (see #1918)
* [x] org.openhab.core.types.StateDescription​ (see #1918)

See also the [Deprecated APIs in the JavaDocs](https://next.openhab.org/javadoc/latest/deprecated-list.html).

**Comment by cweitkamp** [comment]
One question related to `StateDescriptionProvider` - Removing this interface looks quite easy but how do we continue with `StateDescription` and `StateDescriptionFragment`? The latter is preferred one, but the first one is used in e.g. `ChannelType`. Should the usage of `StateDescription` be replaced by `StateDescriptionFragment` for `ChannelType`?

We definitely can / should extend the `ChannelTypeBuilder` (`StateChannelTypeBuilder` and its implementation `StateChannelTypeBuilderImpl`) by a new method `withStateDescriptionFragment()` to improve the usage.

**Comment by lolodomo** [comment]
Why UpnpDiscoveryParticipant and MDNSDiscoveryParticipant are deprecated ?
I think UpnpDiscoveryParticipant is used by almost all bindings relying on UPnP for discovery.

**Comment by wborn** [comment]
`org.openhab.core.config.discovery.UpnpDiscoveryParticipant` is deprecated because it moved to its own bundle, i.e. you should use `org.openhab.core.config.discovery.upnp.UpnpDiscoveryParticipant` instead.

**Comment by lolodomo** [comment]
Ok, sorry for the useless remark.

**Comment by wborn** [comment]
No problem! I think there aren't any add-ons using it these days. So it will nicely clean up classes that still use the old deprecated class for backwards compatibility. Removing it will also no longer result in IDEs considering it as import candidate whenever you add `implements  UpnpDiscoveryParticipant` to a class, which might again result in using the deprecated class.

**Comment by wborn** [comment]
While working on https://github.com/openhab/openhab-core/pull/1494 I also found a helpful list of public [Deprecated APIs in the JavaDocs](https://next.openhab.org/javadoc/latest/deprecated-list.html).

**Comment by kaikreuzer** [comment]
All done here, @wborn?

**Comment by wborn** [comment]
We've already fixed many deprecations but according to the [Deprecated API](https://next.openhab.org/javadoc/latest/deprecated-list.html) list there are still a few more to go.

**Comment by kaikreuzer** [comment]
@wborn This is tagged for the OH3 release - do you have an overview of what is realistic to finish of the open topics listed in the description? Are we blocked anywhere because too many bindings use it?
