### ISSUE TITLE
OH4 Tasks

### ISSUE THREAD

**Issue by J-N-K** [openhab/openhab-core#3230]
- [ ] Upgrade to minimum Java 17 (PR #2994)

Need to be done in this order

- [ ] Upgrade to new WatchService (PR #3004)
- [ ] Change to addon.xml from binding.xml (PR #3050)

Independent Changes 

- [ ] Upgrade Karaf to 4.4.x 
- [ ] Refactor DSL rules to an independent add-on (Issue #3233)

**Comment by rkoshak** [comment]
Maybe not appropriate to list it here (is there a similar issue for openhab-addons?), but shouldn't the Nashorn addon from the marketplace be brought in to the openhab-addons repo as part of OH 4? Then a decision would need to be made whether or not it should be automatically installed by default (like rrd4j) or not (I'd vote for not, assuming the porting of Blockly to JS Scripting is done before that.)

This seems like a great opportunity to split out Rules DSL into it's own add-on too. I'm not sure that's required for OH 4 though, but I think it would be a good idea.

**Comment by J-N-K** [comment]
Pleas emote that there is also https://github.com/openhab/openhab-distro/issues/1316 which already covers some of your points. I had a quick look at refactoring DSL rules to an add-on, but that requires a bit more work.

**Comment by florian-h05** [comment]
> assuming the porting of Blockly to JS Scripting is done before that

I expect it to be — I created the code that automatically switches from Nashorn to GraalJS by modifying the MIME type and ported the logging blocks and @stefan-hoehn ported another block categories two weeks ago. You can have a look at https://github.com/stefan-hoehn/openhab-webui/commits/blockly_jsscripting. After the 3.4.0 Stable Release, I‘ve to take care of a few things in openhab-js but I am planning to ported a few other blocks over the holidays.

**Comment by cweitkamp** [comment]
In the past we tried to use GitHub Projects to keep track of issues and pull requests for separate OH version ( see https://github.com/orgs/openhab/projects?type=classic ). I am not sure if someone tracked and kept it up to date all the time but maybe we should take a second look into the tool.

**Comment by florian-h05** [comment]
Sound like a good suggestion @cweitkamp and IMO would make our lives much easier as we have one central place to track everything that‘s important.

**Comment by J-N-K** [comment]
I already addd a project. Can you see and edit that?

**Comment by florian-h05** [comment]
I can see and edit the project: I‘ve updated the view to include the repo and labels, but to hide assignees.

**Comment by cweitkamp** [comment]
Yes, I can see it an edit it.

**Comment by stefan-hoehn** [comment]
@florian-h05 Should we put the our blockly jscripting issue to the board as well and add all the tasks that need to be done?

**Comment by florian-h05** [comment]
Yes, we should add this. But IMO we should create a new issue in webui, reference the old PR and close the old PR. Discussing at a PR is not so great IMO.
In the new issue we can also add todos and describe our approach.

**Comment by wborn** [comment]
@kaikreuzer can you make the project public in the [settings](https://github.com/orgs/openhab/projects/7/settings)?

Changing the visibility is restricted to owners when you create one:

![Screenshot from 2022-12-19 16-13-51](https://user-images.githubusercontent.com/12213581/208458480-2514f931-8519-4dd3-a8d9-61c1c60ec2e1.png)

**Comment by digitaldan** [comment]
>@kaikreuzer can you make the project public in the [settings](https://github.com/orgs/openhab/projects/7/settings)?

Done.

**Comment by kaikreuzer** [comment]
Ok, you were quicker - I was just about to do it. 😉

**Comment by J-N-K** [comment]
Since we track it in the project -> Closed.

**Comment by florian-h05** [comment]
Why is the project closed??
