### ISSUE TITLE
Fix and reenable disabled integration tests

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-core#698]
Some integration tests are still disabled ever since the migration from PDE to bnd. As new PRs are merged these tests will only be broken even more. So it would certainly help if we can fix and reenable these ASAP.

The currently disabled tests (commented in [itests/pom.xml](https://github.com/openhab/openhab-core/blob/master/itests/pom.xml#L23)) are:

- [x] org.openhab.core.automation.integration.tests (#1061)
- [x] org.openhab.core.automation.module.core.tests (#1062)
- [x] org.openhab.core.automation.module.script.defaultscope.tests (#1062)
- [x] org.openhab.core.automation.module.script.tests (#1062)
- [x] org.openhab.core.automation.module.timer.tests (#1062)
- [x] org.openhab.core.config.discovery.usbserial.linuxsysfs.tests (#1065)
- [x] org.openhab.core.config.discovery.usbserial.tests (#1065)
- [x] org.openhab.core.config.dispatch.tests (#995)
- [x] org.openhab.core.config.xml.tests (#971)
- [x] org.openhab.core.io.http.tests (#700)
- [x] ~org.openhab.core.io.rest.sse.tests~ moved to pure unit tests (#1044)
- [x] ~org.openhab.core.io.rest.tests~ moved to pure unit tests (#1055)
- [x] ~org.openhab.core.io.transport.mqtt.tests~ moved to pure unit tests (#1056)
- [x] ~org.openhab.core.io.transport.upnp.tests~ moved to pure unit tests (#1057)
- [x] org.openhab.core.magic.tests (#756)
- [x] org.openhab.core.model.core.tests (#728)
- [x] org.openhab.core.model.item.tests (#735)
- [x] org.openhab.core.model.lsp.tests (#730)
- [x] org.openhab.core.model.persistence.tests (#729)
- [x] org.openhab.core.model.rule.tests (#736)
- [x] org.openhab.core.model.script.tests (#737)
- [x] org.openhab.core.semantics.tests (#697)

I've already created a PR (https://github.com/openhab/openhab-core/pull/697) for reenabling `org.openhab.core.semantics.tests`. :-)

**Comment by cweitkamp** [comment]
`org.openhab.core.magic.tests` is part of #655.

**Comment by cweitkamp** [comment]
FYI: I am working on: `org.openhab.core.model.*`

**Comment by openhab-5iver** [comment]
I've been working on the automation tests. There is also a failure in org.openhab.core.automation.tests, which isn't in the list.

**Comment by maggu2810** [comment]
The list contains the ones that has not been enabled at issue creation time.
The ones that has already been enabled are not part of this list.

**Comment by openhab-5iver** [comment]
I'm still unable to run tests in the IDE. Are they working for the rest of you, or are you running them from commandline?

**Comment by wborn** [comment]
Yes it works fine for me!

Maybe it helps to remove the itests projects, run `git clean -dfx` in the `itests` directory, and then reimport these as existing Maven projects.

Then it should be possible to execute the tests by right clicking a `itests.bndrun`, choose "Run As" or "Debug As" followed by "Bnd OSGi Test Launcher (JUnit)".

See screenshot below:

![itest](https://user-images.githubusercontent.com/12213581/62859812-92ac6f00-bcfe-11e9-9eef-fb6dd891c856.png)

**Comment by cweitkamp** [comment]
Great to have it working again. Now we have to watch for some of the tests which are failing occasionally and try to improve their stability.

:+1:

**Comment by wborn** [comment]
Yes very nice indeed and thanks a lot for helping out @cweitkamp! :+1: 

I'd thought fixing all of them would take the rest of the week... but for a nice change fixing them was easier than expected. :smile: 

I'll try to fix any unstable ones as well. I also plan on creating PRs for moving the many **non**-integration tests to the respective projects where possible. That way they are easier to run and maintain.

**Comment by cweitkamp** [comment]
That is cool :sunglasses: . Ping me if you need a hand.

**Comment by lolodomo** [comment]
When I run them on my PC (Windows 10), 3 bundles are failing. Issues are opened for each of them with logs.

**Comment by wborn** [comment]
Thanks for creating the issues @lolodomo. Maybe when I have some time I can check it with a Windows VM. It's probably again due to differences in line endings, path separators, default encodings or timing differences. :wink:

**Comment by cweitkamp** [comment]
@wborn Very nice work. Thank you very much. I think that will help a lot for maintenance in the future - and for developing too. :+1:

**Comment by wborn** [comment]
Thanks for the quick reviews and merge @cweitkamp! There are still a few itests projects I have to check but the majority has been done now. :-) (I'll make this remark here too to keep the discussion at a central place ;-) )
