### ISSUE TITLE
Allow multiple values for default configuration

### ISSUE THREAD

**Issue by cweitkamp** [openhab/openhab-core#998]
The "default" value of a configuration is always a String. This could be a problem if a service / thing / channels uses a configuration description defined with `multiple="true"` and more than one default value should be available (see e.g. #919).

I worked out a three step plan to get it supported:

1. [x] Extend Config Dispatcher to support values containing a list of configuration options (see #999)
2. [x] Extend REST interface to return a list for `defaultValue` if `multiple="true"` (see #1031)
3. [x] (later) Consider more than one value(s) when applying the default value for Things and Channels. (see #1067)

My research on item 2:

When adding a default value for a service in the configuration description like the following example it will not be applied immediately:
```
	<config-description uri="system:ephemeris">
		<parameter name="dayset-weekend" type="text" required="true" multiple="true">
			<label>Weekend Days</label>
			<description>List of usual non workable days.</description>
			<default>SATURDAY,SUNDAY</default>
		</parameter>
	</config-description>
```

The wrong listing in Paper UI ([as described here](https://user-images.githubusercontent.com/12213581/62833289-aa232380-bc3c-11e9-8566-3f5f92ca7219.png)) results from a UI side merge of the configuration options and the default value. The UI calls the REST interface for information:

Get the configuration description (GET /rest/config-descriptions/system:ephemeris, options for parameters `country` and `region` are truncated):
```
{
  "uri": "system:ephemeris",
  "parameters": [
    {
      "defaultValue": "SATURDAY,SUNDAY",
      "description": "List of usual non workable days.",
      "label": "Weekend Days",
      "name": "dayset-weekend",
      "required": true,
      "type": "TEXT",
      "readOnly": false,
      "multiple": true,
      "advanced": false,
      "verify": false,
      "limitToOptions": true,
      "options": [
        {
          "label": "Montag",
          "value": "MONDAY"
        },
        {
          "label": "Dienstag",
          "value": "TUESDAY"
        },
        {
          "label": "Mittwoch",
          "value": "WEDNESDAY"
        },
        {
          "label": "Donnerstag",
          "value": "THURSDAY"
        },
        {
          "label": "Freitag",
          "value": "FRIDAY"
        },
        {
          "label": "Samstag",
          "value": "SATURDAY"
        },
        {
          "label": "Sonntag",
          "value": "SUNDAY"
        }
      ],
      "filterCriteria": [
      ]
    },
    {
      "description": "Get the holidays for a specific country (e.g. United States of America = \"us\").",
      "label": "Country",
      "name": "country",
      "required": false,
      "type": "TEXT",
      "readOnly": false,
      "multiple": false,
      "advanced": false,
      "verify": false,
      "limitToOptions": true,
      "options": [
        {
          "label": "Mauritania",
          "value": "mr"
        },
        ...
      ],
      "filterCriteria": [
      ]
    },
    {
      "description": "Get the holidays for a specific state (e.g. New York = \"ny\").",
      "label": "Region",
      "name": "region",
      "required": false,
      "type": "TEXT",
      "readOnly": false,
      "multiple": false,
      "advanced": false,
      "verify": false,
      "limitToOptions": true,
      "options": [
        {
          "label": "Rhineland-Palatinate",
          "value": "rp"
        },
        ....
      ],
      "filterCriteria": [
      ]
    },
    {
      "description": "Get the holidays for a specific city (e.g. New York City = \"nyc\").",
      "label": "City",
      "name": "city",
      "required": false,
      "type": "TEXT",
      "readOnly": false,
      "multiple": false,
      "advanced": false,
      "verify": false,
      "limitToOptions": true,
      "options": [
      ],
      "filterCriteria": [
      ]
    }
  ],
  "parameterGroups": [
  ]
}
```

Get current configuration (GET /rest/services/org.openhab.ephemeris/config, example after a restart with no configuration):
```
{
}
```

Get current configuration (GET /rest/services/org.openhab.ephemeris/config, example after applying a textual configuration) - will be changed by #999:
```
{
    "dayset-weekend": "SATURDAY,SUNDAY"

}
```

Get current configuration (GET /rest/services/org.openhab.ephemeris/config, example after applying a configuration via REST interface) - expected result:
```
{
    "dayset-weekend": [
        "SATURDAY",
        "SUNDAY"
    ]
}
```

**Comment by cweitkamp** [comment]
Everything done. We can close this issue now.
